import { userObject } from "./typeDef";

export const jobPostings = [
  {
    title: "Senior UI/UX Designer",
    company: "Creative Studio",
    location: "New York, NY",
    priceRange: "$70,000 - $90,000",
    jobProximity: "Fully Remote",
    jobHours: "6",
    experience: "Intermediate",
    skills: ["Adobe XD", "Figma", "Photoshop", "Illustrator"],
    role: "Design",
    country: "USA",
  },
  {
    title: "Frontend Developer",
    company: "Tech Innovators",
    location: "San Francisco, CA",
    priceRange: "$120,000 - $150,000",
    jobProximity: "Hybrid",
    jobHours: "8",
    experience: "Senior level",
    skills: ["React", "TypeScript", "CSS", "Tailwind CSS"],
    role: "Engineering",
    country: "USA",
  },
  {
    title: "Graphic Designer",
    company: "Design Corp",
    location: "Lagos, Nigeria",
    priceRange: "$60,000 - $80,000",
    jobProximity: "Remote",
    jobHours: "6",
    experience: "Intermediate",
    skills: ["Illustrator", "Photoshop", "InDesign"],
    role: "Design",
    country: "Nigeria",
  },
  {
    title: "Backend Developer",
    company: "Backend Solutions",
    location: "Chicago, IL",
    priceRange: "$80,000 - $110,000",
    jobProximity: "Full-time",
    jobHours: "10",
    experience: "Senior level",
    skills: ["Node.js", "Express", "MongoDB", "SQL"],
    role: "Engineering",
    country: "USA",
  },
  {
    title: "Product Manager",
    company: "Market Leaders",
    location: "Miami, FL",
    priceRange: "$100,000 - $130,000",
    jobProximity: "Fully Remote",
    jobHours: "8",
    experience: "C-level",
    skills: ["Agile", "Scrum", "JIRA", "Product Strategy"],
    role: "Operations",
    country: "USA",
  },
  {
    title: "Data Scientist",
    company: "Analytics Hub",
    location: "Toronto, Canada",
    priceRange: "$110,000 - $140,000",
    jobProximity: "Hybrid",
    jobHours: "8",
    experience: "Senior level",
    skills: ["Python", "R", "SQL", "Machine Learning"],
    role: "Engineering",
    country: "Canada",
  },
  {
    title: "Marketing Specialist",
    company: "Brand Boosters",
    location: "Nairobi, Kenya",
    priceRange: "$70,000 - $90,000",
    jobProximity: "Full-time",
    jobHours: "8",
    experience: "Intermediate",
    skills: ["SEO", "Content Marketing", "Google Analytics"],
    role: "Marketing",
    country: "Kenya",
  },
  {
    title: "Mobile App Developer",
    company: "App Creators",
    location: "London, UK",
    priceRange: "$100,000 - $130,000",
    jobProximity: "Fully Remote",
    jobHours: "8",
    experience: "Senior level",
    skills: ["Flutter", "React Native", "Kotlin", "Swift"],
    role: "Engineering",
    country: "UK",
  },
  {
    title: "DevOps Engineer",
    company: "Cloud Solutions",
    location: "Berlin, Germany",
    priceRange: "$95,000 - $120,000",
    jobProximity: "Hybrid",
    jobHours: "12",
    experience: "Intermediate",
    skills: ["AWS", "Docker", "Kubernetes", "CI/CD"],
    role: "Engineering",
    country: "Germany",
  },
  {
    title: "Business Analyst",
    company: "Finance Experts",
    location: "Sydney, Australia",
    priceRange: "$80,000 - $100,000",
    jobProximity: "Remote",
    jobHours: "10",
    experience: "Senior level",
    skills: ["SQL", "Tableau", "Business Intelligence"],
    role: "Finance",
    country: "Australia",
  },
  {
    title: "Content Writer",
    company: "Creative Words",
    location: "Philadelphia, PA",
    priceRange: "$60,000 - $75,000",
    jobProximity: "Fully Remote",
    jobHours: "6",
    experience: "Intermediate",
    skills: ["SEO", "Content Creation", "Copywriting"],
    role: "Marketing",
    country: "USA",
  },
  {
    title: "Sales Manager",
    company: "Sales Experts",
    location: "Tokyo, Japan",
    priceRange: "$90,000 - $120,000",
    jobProximity: "Full-time",
    jobHours: "12",
    experience: "Senior level",
    skills: ["Salesforce", "CRM", "Lead Generation"],
    role: "Sales",
    country: "Japan",
  },
  {
    title: "HR Specialist",
    company: "HR Solutions",
    location: "San Diego, CA",
    priceRange: "$70,000 - $90,000",
    jobProximity: "Hybrid",
    jobHours: "10",
    experience: "Intermediate",
    skills: ["Recruitment", "Employee Relations", "HRIS"],
    role: "Operations",
    country: "USA",
  },
  {
    title: "Systems Administrator",
    company: "IT Support Inc.",
    location: "Phoenix, AZ",
    priceRange: "$75,000 - $95,000",
    jobProximity: "Full-time",
    jobHours: "8",
    experience: "Senior level",
    skills: ["Linux", "Windows Server", "Network Security"],
    role: "Engineering",
    country: "USA",
  },
  {
    title: "UI Developer",
    company: "Web Wizards",
    location: "Johannesburg, South Africa",
    priceRange: "$85,000 - $110,000",
    jobProximity: "Remote",
    jobHours: "12",
    experience: "Intermediate",
    skills: ["HTML", "CSS", "JavaScript", "React"],
    role: "Engineering",
    country: "South Africa",
  },
  {
    title: "Data Analyst",
    company: "Data Insights",
    location: "San Jose, CA",
    priceRange: "$90,000 - $115,000",
    jobProximity: "Fully Remote",
    jobHours: "6",
    experience: "Senior level",
    skills: ["SQL", "Excel", "Data Visualization"],
    role: "Engineering",
    country: "USA",
  },
  {
    title: "Security Engineer",
    company: "SecureTech",
    location: "Portland, OR",
    priceRange: "$100,000 - $130,000",
    jobProximity: "Hybrid",
    jobHours: "12",
    experience: "C-level",
    skills: ["Cybersecurity", "Penetration Testing", "Incident Response"],
    role: "Engineering",
    country: "USA",
  },
  {
    title: "Operations Manager",
    company: "Operations Hub",
    location: "Orlando, FL",
    priceRange: "$110,000 - $140,000",
    jobProximity: "Full-time",
    jobHours: "10",
    experience: "Senior level",
    skills: ["Project Management", "Lean Six Sigma", "Operations Strategy"],
    role: "Operations",
    country: "USA",
  },
  {
    title: "Customer Support Specialist",
    company: "Support Team",
    location: "Las Vegas, NV",
    priceRange: "$50,000 - $65,000",
    jobProximity: "Fully Remote",
    jobHours: "12",
    experience: "Intermediate",
    skills: ["Customer Service", "Help Desk", "Technical Support"],
    role: "Operations",
    country: "USA",
  },
  {
    title: "IT Project Manager",
    company: "Tech Leaders",
    location: "Charlotte, NC",
    priceRange: "$95,000 - $125,000",
    jobProximity: "Hybrid",
    jobHours: "8",
    experience: "Senior level",
    skills: ["Project Management", "Scrum", "Agile"],
    role: "Operations",
    country: "USA",
  },
];

export const activeJobApplication = [
  {
    title: "Senior UI/UX Designer",
    company: "Creative Studio",
    location: "New York, NY",
    priceRange: "$70,000 - $90,000",
    jobProximity: "Fully Remote",
    status: "Under Review",
  },
  {
    title: "Senior Frontend Developer",
    company: "Tech Innovators",
    location: "San Francisco, CA",
    priceRange: "$120,000 - $150,000",
    jobProximity: "Hybrid",
    status: "Declined",
  },
  {
    title: "Graphic Designer",
    company: "Design Corp",
    location: "Lagos, Nigeria",
    priceRange: "$60,000 - $80,000",
    jobProximity: "Remote",
    status: "Hired",
  },
  {
    title: "Backend Developer",
    company: "Backend Solutions",
    location: "Berlin, Germany",
    priceRange: "$80,000 - $100,000",
    jobProximity: "On-site",
    status: "Under Review",
  },
  {
    title: "Project Manager",
    company: "Project Pros",
    location: "London, UK",
    priceRange: "£50,000 - £70,000",
    jobProximity: "Fully Remote",
    status: "Hired",
  },
  {
    title: "Data Scientist",
    company: "Data Insights",
    location: "Toronto, Canada",
    priceRange: "$110,000 - $130,000",
    jobProximity: "Hybrid",
    status: "Under Review",
  },
  {
    title: "Product Designer",
    company: "Design Hub",
    location: "Paris, France",
    priceRange: "€60,000 - €80,000",
    jobProximity: "On-site",
    status: "Declined",
  },
  {
    title: "DevOps Engineer",
    company: "Cloud Solutions",
    location: "Sydney, Australia",
    priceRange: "AU$100,000 - AU$120,000",
    jobProximity: "Remote",
    status: "Under Review",
  },
  {
    title: "Mobile Developer",
    company: "App Creators",
    location: "Tokyo, Japan",
    priceRange: "¥8,000,000 - ¥10,000,000",
    jobProximity: "Hybrid",
    status: "Hired",
  },
  {
    title: "Marketing Specialist",
    company: "Market Leaders",
    location: "São Paulo, Brazil",
    priceRange: "R$80,000 - R$100,000",
    jobProximity: "Fully Remote",
    status: "Declined",
  },
  {
    title: "Software Engineer",
    company: "Tech Pioneers",
    location: "Austin, TX",
    priceRange: "$90,000 - $110,000",
    jobProximity: "On-site",
    status: "Under Review",
  },
  {
    title: "QA Engineer",
    company: "Quality Assured",
    location: "Mumbai, India",
    priceRange: "₹800,000 - ₹1,000,000",
    jobProximity: "Remote",
    status: "Hired",
  },
  {
    title: "Business Analyst",
    company: "Business Solutions",
    location: "Chicago, IL",
    priceRange: "$85,000 - $105,000",
    jobProximity: "Hybrid",
    status: "Under Review",
  },
  {
    title: "System Administrator",
    company: "IT Services",
    location: "Cape Town, South Africa",
    priceRange: "R500,000 - R700,000",
    jobProximity: "On-site",
    status: "Declined",
  },
  {
    title: "AI Researcher",
    company: "AI Innovations",
    location: "Tel Aviv, Israel",
    priceRange: "$100,000 - $120,000",
    jobProximity: "Remote",
    status: "Under Review",
  },
  {
    title: "Network Engineer",
    company: "Network Experts",
    location: "Moscow, Russia",
    priceRange: "₽3,000,000 - ₽4,000,000",
    jobProximity: "On-site",
    status: "Declined",
  },
  {
    title: "Technical Writer",
    company: "Content Creators",
    location: "Dublin, Ireland",
    priceRange: "€40,000 - €60,000",
    jobProximity: "Remote",
    status: "Hired",
  },
  {
    title: "Blockchain Developer",
    company: "Crypto Solutions",
    location: "Zurich, Switzerland",
    priceRange: "CHF 120,000 - CHF 150,000",
    jobProximity: "Hybrid",
    status: "Under Review",
  },
  {
    title: "IT Support Specialist",
    company: "Support Squad",
    location: "Hong Kong",
    priceRange: "HK$400,000 - HK$500,000",
    jobProximity: "On-site",
    status: "Under Review",
  },
  {
    title: "Cybersecurity Analyst",
    company: "SecureTech",
    location: "Dubai, UAE",
    priceRange: "AED 300,000 - AED 400,000",
    jobProximity: "Remote",
    status: "Declined",
  },
];

interface JobPosted {
  title: string;
  department: string;
  location: string;
  employmentType: string;
  salaryRange: string;
  status: string;
  candidates?: userObject[];
}

export const jobsPostedByCompany: JobPosted[] = [
  {
    title: "Frontend Developer",
    department: "Engineering",
    location: "New York, NY",
    employmentType: "Full-time",
    salaryRange: "$80,000 - $100,000",
    status: "Open",
    candidates: [
      {
        firstName: "Ditimi",
        lastName: "Podeke",
        profileImage: null,
        phoneNumber: "8169537139",
        countryCode: "+234",
        emailAddress: "ditimi.podeke@example.com",
        industry: "Engineering",
        password: "securepassword123",
        role: "Software Engineer",
        experienceYears: "4-6 years",
        experienceLevel: "Senior",
        preference: "Remote",
        country: "Nigeria",
        location: "Lagos, Nigeria",
        filename: "Profile.pdf",
        accountStatus: "Approved",
        hex: "#123456",
        linkedInUrl: "www.linkedin.com/in/ditimi-podeke-63b8a11a6/",
      },
      {
        firstName: "Folashade",
        lastName: "Podeke",
        profileImage: null,
        phoneNumber: "8169537139",
        countryCode: "+234",
        emailAddress: "ditimi.podeke@example.com",
        industry: "Engineering",
        password: "securepassword123",
        role: "Software Engineer",
        experienceYears: "4-6 years",
        experienceLevel: "Senior",
        preference: "Remote",
        country: "Nigeria",
        location: "Lagos, Nigeria",
        filename: "Profile.pdf",
        accountStatus: "Approved",
        hex: "#123456",
        linkedInUrl: "www.linkedin.com/in/ditimi-podeke-63b8a11a6/",
      },
      {
        firstName: "Mary",
        lastName: "Podeke",
        profileImage: null,
        phoneNumber: "8169537139",
        countryCode: "+234",
        emailAddress: "ditimi.podeke@example.com",
        industry: "Engineering",
        password: "securepassword123",
        role: "Software Engineer",
        experienceYears: "4-6 years",
        experienceLevel: "Senior",
        preference: "Remote",
        country: "Nigeria",
        location: "Lagos, Nigeria",
        filename: "Profile.pdf",
        accountStatus: "Approved",
        hex: "#123456",
        linkedInUrl: "www.linkedin.com/in/ditimi-podeke-63b8a11a6/",
      },
      // Add up to 2 more candidates if needed
    ],
  },
  {
    title: "Backend Developer",
    department: "Engineering",
    location: "San Francisco, CA",
    employmentType: "Full-time",
    salaryRange: "$90,000 - $110,000",
    status: "Open",
    candidates: [
      {
        firstName: "Jane",
        lastName: "Doe",
        profileImage: null,
        phoneNumber: "1234567890",
        countryCode: "+1",
        emailAddress: "jane.doe@example.com",
        industry: "Engineering",
        password: "securepassword123",
        role: "Backend Developer",
        experienceYears: "3-5 years",
        experienceLevel: "Intermediate",
        preference: "On-site",
        country: "United States",
        location: "San Francisco, CA",
        filename: "Profile.pdf",
        accountStatus: "Approved",
        hex: "#654321",
        linkedInUrl: "www.linkedin.com/in/jane-doe/",
      },
      // Add up to 2 more candidates if needed
    ],
  },
  {
    title: "UX Designer",
    department: "Design",
    location: "Remote",
    employmentType: "Contract",
    salaryRange: "$60,000 - $80,000",
    status: "Open",
    candidates: [
      {
        firstName: "John",
        lastName: "Smith",
        profileImage: null,
        phoneNumber: "0987654321",
        countryCode: "+1",
        emailAddress: "john.smith@example.com",
        industry: "Design",
        password: "securepassword123",
        role: "UX Designer",
        experienceYears: "2-4 years",
        experienceLevel: "Intermediate",
        preference: "Remote",
        country: "United States",
        location: "New York, NY",
        filename: "Profile.pdf",
        accountStatus: "Approved",
        hex: "#abcdef",
        linkedInUrl: "www.linkedin.com/in/john-smith/",
      },
      // Add up to 2 more candidates if needed
    ],
  },
  {
    title: "Product Manager",
    department: "Product",
    location: "Austin, TX",
    employmentType: "Full-time",
    salaryRange: "$100,000 - $120,000",
    status: "Closed",
    candidates: [
      {
        firstName: "Alice",
        lastName: "Johnson",
        profileImage: null,
        phoneNumber: "5647382910",
        countryCode: "+1",
        emailAddress: "alice.johnson@example.com",
        industry: "Product",
        password: "securepassword123",
        role: "Product Manager",
        experienceYears: "5-7 years",
        experienceLevel: "Senior",
        preference: "On-site",
        country: "United States",
        location: "Austin, TX",
        filename: "Profile.pdf",
        accountStatus: "Approved",
        hex: "#a1b2c3",
        linkedInUrl: "www.linkedin.com/in/alice-johnson/",
      },
      // Add up to 2 more candidates if needed
    ],
  },
  {
    title: "Data Scientist",
    department: "Data Science",
    location: "Boston, MA",
    employmentType: "Full-time",
    salaryRange: "$110,000 - $130,000",
    status: "Open",
    candidates: [
      {
        firstName: "Bob",
        lastName: "Brown",
        profileImage: null,
        phoneNumber: "1827364530",
        countryCode: "+1",
        emailAddress: "bob.brown@example.com",
        industry: "Data Science",
        password: "securepassword123",
        role: "Data Scientist",
        experienceYears: "6-8 years",
        experienceLevel: "Senior",
        preference: "On-site",
        country: "United States",
        location: "Boston, MA",
        filename: "Profile.pdf",
        accountStatus: "Approved",
        hex: "#d4e5f6",
        linkedInUrl: "www.linkedin.com/in/bob-brown/",
      },
      // Add up to 2 more candidates if needed
    ],
  },
  {
    title: "Marketing Specialist",
    department: "Marketing",
    location: "Chicago, IL",
    employmentType: "Part-time",
    salaryRange: "$50,000 - $70,000",
    status: "Closed",
    candidates: [
      {
        firstName: "Cathy",
        lastName: "White",
        profileImage: null,
        phoneNumber: "9182736450",
        countryCode: "+1",
        emailAddress: "cathy.white@example.com",
        industry: "Marketing",
        password: "securepassword123",
        role: "Marketing Specialist",
        experienceYears: "3-5 years",
        experienceLevel: "Intermediate",
        preference: "On-site",
        country: "United States",
        location: "Chicago, IL",
        filename: "Profile.pdf",
        accountStatus: "Approved",
        hex: "#f7a8b9",
        linkedInUrl: "www.linkedin.com/in/cathy-white/",
      },
      // Add up to 2 more candidates if needed
    ],
  },
  {
    title: "Sales Representative",
    department: "Sales",
    location: "Seattle, WA",
    employmentType: "Full-time",
    salaryRange: "$70,000 - $90,000",
    status: "Open",
    candidates: [
      {
        firstName: "David",
        lastName: "Lee",
        profileImage: null,
        phoneNumber: "5647381920",
        countryCode: "+1",
        emailAddress: "david.lee@example.com",
        industry: "Sales",
        password: "securepassword123",
        role: "Sales Representative",
        experienceYears: "2-4 years",
        experienceLevel: "Intermediate",
        preference: "On-site",
        country: "United States",
        location: "Seattle, WA",
        filename: "Profile.pdf",
        accountStatus: "Approved",
        hex: "#00ff00",
        linkedInUrl: "www.linkedin.com/in/david-lee/",
      },
      // Add up to 2 more candidates if needed
    ],
  },
  {
    title: "HR Manager",
    department: "Human Resources",
    location: "Miami, FL",
    employmentType: "Full-time",
    salaryRange: "$90,000 - $110,000",
    status: "Open",
    candidates: [
      {
        firstName: "Eva",
        lastName: "Green",
        profileImage: null,
        phoneNumber: "1726354890",
        countryCode: "+1",
        emailAddress: "eva.green@example.com",
        industry: "Human Resources",
        password: "securepassword123",
        role: "HR Manager",
        experienceYears: "5-7 years",
        experienceLevel: "Senior",
        preference: "On-site",
        country: "United States",
        location: "Miami, FL",
        filename: "Profile.pdf",
        accountStatus: "Approved",
        hex: "#ff00ff",
        linkedInUrl: "www.linkedin.com/in/eva-green/",
      },
      // Add up to 2 more candidates if needed
    ],
  },
  {
    title: "DevOps Engineer",
    department: "Engineering",
    location: "Remote",
    employmentType: "Full-time",
    salaryRange: "$100,000 - $120,000",
    status: "Closed",
    candidates: [
      {
        firstName: "Frank",
        lastName: "Hall",
        profileImage: null,
        phoneNumber: "2837465820",
        countryCode: "+1",
        emailAddress: "frank.hall@example.com",
        industry: "Engineering",
        password: "securepassword123",
        role: "DevOps Engineer",
        experienceYears: "4-6 years",
        experienceLevel: "Senior",
        preference: "Remote",
        country: "United States",
        location: "Los Angeles, CA",
        filename: "Profile.pdf",
        accountStatus: "Approved",
        hex: "#123abc",
        linkedInUrl: "www.linkedin.com/in/frank-hall/",
      },
      // Add up to 2 more candidates if needed
    ],
  },
  {
    title: "Customer Support Specialist",
    department: "Support",
    location: "Denver, CO",
    employmentType: "Part-time",
    salaryRange: "$40,000 - $60,000",
    status: "Open",
    candidates: [
      {
        firstName: "Grace",
        lastName: "King",
        profileImage: null,
        phoneNumber: "1029384756",
        countryCode: "+1",
        emailAddress: "grace.king@example.com",
        industry: "Support",
        password: "securepassword123",
        role: "Customer Support Specialist",
        experienceYears: "1-3 years",
        experienceLevel: "Junior",
        preference: "On-site",
        country: "United States",
        location: "Denver, CO",
        filename: "Profile.pdf",
        accountStatus: "Approved",
        hex: "#abcdef",
        linkedInUrl: "www.linkedin.com/in/grace-king/",
      },
      // Add up to 2 more candidates if needed
    ],
  },
];

export const hiredCandidates: userObject[] = [
  {
    firstName: "Ditimi",
    lastName: "Podeke",
    profileImage: null,
    phoneNumber: "8169537139",
    countryCode: "+234",
    emailAddress: "ditimi.podeke@example.com",
    industry: "Engineering",
    password: "securepassword123",
    role: "Software Engineer",
    experienceYears: "4-6 years",
    experienceLevel: "Senior",
    preference: "Remote",
    country: "Nigeria",
    location: "Lagos, Nigeria",
    filename: "Profile.pdf",
    accountStatus: "Approved",
    hex: "#123456",
    linkedInUrl: "www.linkedin.com/in/ditimi-podeke-63b8a11a6/",
  },
  {
    firstName: "John",
    lastName: "Doe",
    profileImage: null,
    phoneNumber: "1234567890",
    countryCode: "+1",
    emailAddress: "john.doe@example.com",
    industry: "Marketing",
    password: "securepassword123",
    role: "Marketing Specialist",
    experienceYears: "3-5 years",
    experienceLevel: "Intermediate",
    preference: "Hybrid",
    country: "United States",
    location: "San Francisco, CA",
    filename: "JohnDoeProfile.pdf",
    accountStatus: "Approved",
    hex: "#654321",
    linkedInUrl: "www.linkedin.com/in/john-doe-123456789/",
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    profileImage: null,
    phoneNumber: "9876543210",
    countryCode: "+44",
    emailAddress: "jane.smith@example.com",
    industry: "Design",
    password: "securepassword123",
    role: "UX/UI Designer",
    experienceYears: "5-7 years",
    experienceLevel: "Senior",
    preference: "Remote",
    country: "United Kingdom",
    location: "London, UK",
    filename: "JaneSmithProfile.pdf",
    accountStatus: "Approved",
    hex: "#abcdef",
    linkedInUrl: "www.linkedin.com/in/jane-smith-987654321/",
  },
  {
    firstName: "Carlos",
    lastName: "Gomez",
    profileImage: null,
    phoneNumber: "5551234567",
    countryCode: "+34",
    emailAddress: "carlos.gomez@example.com",
    industry: "Data Science",
    password: "securepassword123",
    role: "Data Scientist",
    experienceYears: "6-8 years",
    experienceLevel: "Senior",
    preference: "On-site",
    country: "Spain",
    location: "Madrid, Spain",
    filename: "CarlosGomezProfile.pdf",
    accountStatus: "Approved",
    hex: "#789abc",
    linkedInUrl: "www.linkedin.com/in/carlos-gomez-789abc123/",
  },
  {
    firstName: "Linda",
    lastName: "Taylor",
    profileImage: null,
    phoneNumber: "4445556667",
    countryCode: "+61",
    emailAddress: "linda.taylor@example.com",
    industry: "Human Resources",
    password: "securepassword123",
    role: "HR Manager",
    experienceYears: "8-10 years",
    experienceLevel: "Senior",
    preference: "Hybrid",
    country: "Australia",
    location: "Sydney, Australia",
    filename: "LindaTaylorProfile.pdf",
    accountStatus: "Approved",
    hex: "#cde789",
    linkedInUrl: "www.linkedin.com/in/linda-taylor-444555666/",
  },
];
