export const jobPostings = [
  {
    location: "New York, NY",
    priceRange: "$80,000 - $100,000",
    jobProximity: "Full-time",
    jobHours: "8",
    experience: "Senior level",
    skills: ["Adobe XD", "Figma", "Photoshop", "Illustrator"],
  },
  {
    location: "San Francisco, CA",
    priceRange: "$120,000 - $150,000",
    jobProximity: "Fully Remote",
    jobHours: "6",
    experience: "C-level",
    skills: ["Figma", "Photoshop"],
  },
  {
    location: "Austin, TX",
    priceRange: "$70,000 - $90,000",
    jobProximity: "Hybrid",
    jobHours: "10",
    experience: "Intermediate",
    skills: ["Adobe XD", "Illustrator"],
  },
  {
    location: "Chicago, IL",
    priceRange: "$60,000 - $80,000",
    jobProximity: "Relocation",
    jobHours: "12",
    experience: "Senior level",
    skills: ["Figma", "Photoshop", "Illustrator"],
  },
  {
    location: "Miami, FL",
    priceRange: "$75,000 - $95,000",
    jobProximity: "Full-time",
    jobHours: "10",
    experience: "Intermediate",
    skills: ["Adobe XD", "Photoshop"],
  },
  {
    location: "Boston, MA",
    priceRange: "$85,000 - $110,000",
    jobProximity: "Fully Remote",
    jobHours: " 12",
    experience: "Senior level",
    skills: ["Figma", "Illustrator"],
  },
  {
    location: "Seattle, WA",
    priceRange: "$90,000 - $120,000",
    jobProximity: "Hybrid",
    jobHours: "8",
    experience: "C-level",
    skills: ["Adobe XD", "Photoshop"],
  },
  {
    location: "Los Angeles, CA",
    priceRange: "$110,000 - $130,000",
    jobProximity: "Full-time",
    jobHours: "12",
    experience: "Senior level",
    skills: ["Figma", "Illustrator"],
  },
  {
    location: "Denver, CO",
    priceRange: "$65,000 - $85,000",
    jobProximity: "Relocation",
    jobHours: "6",
    experience: "Intermediate",
    skills: ["Adobe XD", "Photoshop"],
  },
  {
    location: "Houston, TX",
    priceRange: "$70,000 - $90,000",
    jobProximity: "Fully Remote",
    jobHours: "10",
    experience: "Senior level",
    skills: ["Figma", "Illustrator"],
  },
  {
    location: "Philadelphia, PA",
    priceRange: "$80,000 - $100,000",
    jobProximity: "Hybrid",
    jobHours: "12",
    experience: "C-level",
    skills: ["Adobe XD", "Photoshop"],
  },
  {
    location: "Dallas, TX",
    priceRange: "$75,000 - $95,000",
    jobProximity: "Full-time",
    jobHours: "12",
    experience: "Intermediate",
    skills: ["Figma", "Illustrator"],
  },
  {
    location: "San Diego, CA",
    priceRange: "$85,000 - $110,000",
    jobProximity: "Relocation",
    jobHours: " 8",
    experience: "Senior level",
    skills: ["Adobe XD", "Photoshop"],
  },
  {
    location: "Phoenix, AZ",
    priceRange: "$90,000 - $120,000",
    jobProximity: "Fully Remote",
    jobHours: "8",
    experience: "Intermediate",
    skills: ["Figma", "Illustrator"],
  },
  {
    location: "Atlanta, GA",
    priceRange: "$95,000 - $125,000",
    jobProximity: "Hybrid",
    jobHours: "8",
    experience: "C-level",
    skills: ["Adobe XD", "Photoshop"],
  },
  {
    location: "San Jose, CA",
    priceRange: "$100,000 - $130,000",
    jobProximity: "Full-time",
    jobHours: "8",
    experience: "Senior level",
    skills: ["Figma", "Illustrator"],
  },
  {
    location: "Portland, OR",
    priceRange: "$70,000 - $90,000",
    jobProximity: "Relocation",
    jobHours: "8",
    experience: "Intermediate",
    skills: ["Adobe XD", "Photoshop"],
  },
  {
    location: "Orlando, FL",
    priceRange: "$80,000 - $100,000",
    jobProximity: "Fully Remote",
    jobHours: "10",
    experience: "Senior level",
    skills: ["Figma", "Illustrator"],
  },
  {
    location: "Las Vegas, NV",
    priceRange: "$85,000 - $110,000",
    jobProximity: "Hybrid",
    jobHours: "12",
    experience: "C-level",
    skills: ["Adobe XD", "Photoshop"],
  },
  {
    location: "Charlotte, NC",
    priceRange: "$90,000 - $120,000",
    jobProximity: "Full-time",
    jobHours: "8",
    experience: "Intermediate",
    skills: ["Figma", "Illustrator"],
  },
];
