export const jobPostings = [
  {
    title: "Senior UI/UX Designer",
    company: "Creative Studio",
    location: "New York, NY",
    priceRange: "$70,000 - $90,000",
    jobProximity: "Fully Remote",
    jobHours: "6",
    experience: "Intermediate",
    skills: ["Adobe XD", "Figma", "Photoshop", "Illustrator"],
    role: "Design",
    country: "USA",
  },
  {
    title: "Frontend Developer",
    company: "Tech Innovators",
    location: "San Francisco, CA",
    priceRange: "$120,000 - $150,000",
    jobProximity: "Hybrid",
    jobHours: "8",
    experience: "Senior level",
    skills: ["React", "TypeScript", "CSS", "Tailwind CSS"],
    role: "Engineering",
    country: "USA",
  },
  {
    title: "Graphic Designer",
    company: "Design Corp",
    location: "Lagos, Nigeria",
    priceRange: "$60,000 - $80,000",
    jobProximity: "Relocation",
    jobHours: "6",
    experience: "Intermediate",
    skills: ["Illustrator", "Photoshop", "InDesign"],
    role: "Design",
    country: "Nigeria",
  },
  {
    title: "Backend Developer",
    company: "Backend Solutions",
    location: "Chicago, IL",
    priceRange: "$80,000 - $110,000",
    jobProximity: "Full-time",
    jobHours: "10",
    experience: "Senior level",
    skills: ["Node.js", "Express", "MongoDB", "SQL"],
    role: "Engineering",
    country: "USA",
  },
  {
    title: "Product Manager",
    company: "Market Leaders",
    location: "Miami, FL",
    priceRange: "$100,000 - $130,000",
    jobProximity: "Fully Remote",
    jobHours: "8",
    experience: "C-level",
    skills: ["Agile", "Scrum", "JIRA", "Product Strategy"],
    role: "Operations",
    country: "USA",
  },
  {
    title: "Data Scientist",
    company: "Analytics Hub",
    location: "Toronto, Canada",
    priceRange: "$110,000 - $140,000",
    jobProximity: "Hybrid",
    jobHours: "8",
    experience: "Senior level",
    skills: ["Python", "R", "SQL", "Machine Learning"],
    role: "Engineering",
    country: "Canada",
  },
  {
    title: "Marketing Specialist",
    company: "Brand Boosters",
    location: "Nairobi, Kenya",
    priceRange: "$70,000 - $90,000",
    jobProximity: "Full-time",
    jobHours: "8",
    experience: "Intermediate",
    skills: ["SEO", "Content Marketing", "Google Analytics"],
    role: "Marketing",
    country: "Kenya",
  },
  {
    title: "Mobile App Developer",
    company: "App Creators",
    location: "London, UK",
    priceRange: "$100,000 - $130,000",
    jobProximity: "Fully Remote",
    jobHours: "8",
    experience: "Senior level",
    skills: ["Flutter", "React Native", "Kotlin", "Swift"],
    role: "Engineering",
    country: "UK",
  },
  {
    title: "DevOps Engineer",
    company: "Cloud Solutions",
    location: "Berlin, Germany",
    priceRange: "$95,000 - $120,000",
    jobProximity: "Hybrid",
    jobHours: "12",
    experience: "Intermediate",
    skills: ["AWS", "Docker", "Kubernetes", "CI/CD"],
    role: "Engineering",
    country: "Germany",
  },
  {
    title: "Business Analyst",
    company: "Finance Experts",
    location: "Sydney, Australia",
    priceRange: "$80,000 - $100,000",
    jobProximity: "Relocation",
    jobHours: "10",
    experience: "Senior level",
    skills: ["SQL", "Tableau", "Business Intelligence"],
    role: "Finance",
    country: "Australia",
  },
  {
    title: "Content Writer",
    company: "Creative Words",
    location: "Philadelphia, PA",
    priceRange: "$60,000 - $75,000",
    jobProximity: "Fully Remote",
    jobHours: "6",
    experience: "Intermediate",
    skills: ["SEO", "Content Creation", "Copywriting"],
    role: "Marketing",
    country: "USA",
  },
  {
    title: "Sales Manager",
    company: "Sales Experts",
    location: "Tokyo, Japan",
    priceRange: "$90,000 - $120,000",
    jobProximity: "Full-time",
    jobHours: "12",
    experience: "Senior level",
    skills: ["Salesforce", "CRM", "Lead Generation"],
    role: "Sales",
    country: "Japan",
  },
  {
    title: "HR Specialist",
    company: "HR Solutions",
    location: "San Diego, CA",
    priceRange: "$70,000 - $90,000",
    jobProximity: "Hybrid",
    jobHours: "10",
    experience: "Intermediate",
    skills: ["Recruitment", "Employee Relations", "HRIS"],
    role: "Operations",
    country: "USA",
  },
  {
    title: "Systems Administrator",
    company: "IT Support Inc.",
    location: "Phoenix, AZ",
    priceRange: "$75,000 - $95,000",
    jobProximity: "Full-time",
    jobHours: "8",
    experience: "Senior level",
    skills: ["Linux", "Windows Server", "Network Security"],
    role: "Engineering",
    country: "USA",
  },
  {
    title: "UI Developer",
    company: "Web Wizards",
    location: "Johannesburg, South Africa",
    priceRange: "$85,000 - $110,000",
    jobProximity: "Relocation",
    jobHours: "12",
    experience: "Intermediate",
    skills: ["HTML", "CSS", "JavaScript", "React"],
    role: "Engineering",
    country: "South Africa",
  },
  {
    title: "Data Analyst",
    company: "Data Insights",
    location: "San Jose, CA",
    priceRange: "$90,000 - $115,000",
    jobProximity: "Fully Remote",
    jobHours: "6",
    experience: "Senior level",
    skills: ["SQL", "Excel", "Data Visualization"],
    role: "Engineering",
    country: "USA",
  },
  {
    title: "Security Engineer",
    company: "SecureTech",
    location: "Portland, OR",
    priceRange: "$100,000 - $130,000",
    jobProximity: "Hybrid",
    jobHours: "12",
    experience: "C-level",
    skills: ["Cybersecurity", "Penetration Testing", "Incident Response"],
    role: "Engineering",
    country: "USA",
  },
  {
    title: "Operations Manager",
    company: "Operations Hub",
    location: "Orlando, FL",
    priceRange: "$110,000 - $140,000",
    jobProximity: "Full-time",
    jobHours: "10",
    experience: "Senior level",
    skills: ["Project Management", "Lean Six Sigma", "Operations Strategy"],
    role: "Operations",
    country: "USA",
  },
  {
    title: "Customer Support Specialist",
    company: "Support Team",
    location: "Las Vegas, NV",
    priceRange: "$50,000 - $65,000",
    jobProximity: "Fully Remote",
    jobHours: "12",
    experience: "Intermediate",
    skills: ["Customer Service", "Help Desk", "Technical Support"],
    role: "Operations",
    country: "USA",
  },
  {
    title: "IT Project Manager",
    company: "Tech Leaders",
    location: "Charlotte, NC",
    priceRange: "$95,000 - $125,000",
    jobProximity: "Hybrid",
    jobHours: "8",
    experience: "Senior level",
    skills: ["Project Management", "Scrum", "Agile"],
    role: "Operations",
    country: "USA",
  },
];
