export const searchBarData = [
  {
    label: "Select your Skill",
    options: [
      "Adobe XD",
      "Figma",
      "Photoshop",
      "Illustrator",
      "React",
      "TypeScript",
      "CSS",
      "Tailwind CSS",
      "InDesign",
      "Node.js",
      "Express",
      "MongoDB",
      "SQL",
      "Agile",
      "Scrum",
      "JIRA",
      "Product Strategy",
      "Python",
      "R",
      "Machine Learning",
      "SEO",
      "Content Marketing",
      "Google Analytics",
      "Flutter",
      "React Native",
      "Kotlin",
      "Swift",
      "AWS",
      "Docker",
      "Kubernetes",
      "CI/CD",
      "Tableau",
      "Business Intelligence",
      "Content Creation",
      "Copywriting",
      "Salesforce",
      "CRM",
      "Lead Generation",
      "Recruitment",
      "Employee Relations",
      "HRIS",
      "Linux",
      "Windows Server",
      "Network Security",
      "HTML",
      "JavaScript",
      "Excel",
      "Data Visualization",
      "Cybersecurity",
      "Penetration Testing",
      "Incident Response",
      "Project Management",
      "Lean Six Sigma",
      "Operations Strategy",
      "Customer Service",
      "Help Desk",
      "Technical Support",
    ],
  },
  {
    label: "Select a Role",
    options: [
      "Design",
      "Engineering",
      "Marketing",
      "Sales",
      "Operations",
      "Finance",
      "Communication",
      "Consultancy",
    ],
  },
  {
    label: "Select a Country",
    options: [
      "USA",
      "Nigeria",
      "Kenya",
      "Canada",
      "UK",
      "Germany",
      "Australia",
      "Japan",
      "South Africa",
    ],
  },
];

export const hoursFilter = [
  { item: "6", idx: 0 },
  { item: "8", idx: 1 },
  { item: "10", idx: 2 },
  { item: "12", idx: 3 },
];
export const proximityFilter = [
  { item: "On Site", idx: 4 },
  { item: "Hybrid", idx: 5 },
  { item: "Fully Remote", idx: 6 },
  { item: "Remote", idx: 7 },
];
export const experienceFilter = [
  { item: "Intermediate", idx: 8 },
  { item: "Senior", idx: 9 },
  { item: "C-level", idx: 10 },
];
